name: Build & Deploy file-service

on:
  push:
    branches:
      - master
    paths:
      - 'services/file-service/**'
      - '.github/workflows/file-service.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: anyr00d/file-service
      DEPLOYMENT_REPO: git@github.com:Anyr00d/DropZone-deployment.git

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract short commit SHA
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Copy proto files
        run: cp -r ./proto ./services/audit-service/proto

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/file-service
          file: ./services/file-service/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

      - name: Clone deployment repo
        uses: actions/checkout@v4
        with:
          repository: Anyr00d/DropZone-deployment
          token: ${{ secrets.DEPLOYMENT_REPO_PAT }}
          path: deployment

      - name: Update image tag in Helm values.yaml
        run: |
          sed -i "s|tag: .*|tag: \"${{ steps.vars.outputs.TAG }}\"|" deployment/helm/file-service/values.yaml

      - name: Commit & push to deployment repo
        run: |
          cd deployment
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add helm/file-service/values.yaml
          git commit -m "🚀 Update file-service image to ${{ steps.vars.outputs.TAG }}"
          git push
